version: '3'
services:
  app:
    build: .
    container_name: app
    image: vitoregistry.azurecr.io/app
    restart: unless-stopped
    ports:
      - '80:80'
      - '5000:5000'
    links:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    ports: 
      - '27017:27017'  
