version: '3'
services:
  webapp:
    build: .
    container_name: webapp
    image: vitoregistry.azurecr.io/webapp
    restart: unless-stopped
    ports:
      - '8000:8000'
      - '5000:5000'
    links:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    ports: 
      - '27017:27017'  
